#!/bin/bash

$(./create_env.sh prod)

if [ "$TRAVIS_BRANCH" == "" ]; then
    export VERSION=$(git describe --abbrev=0)
else
    export VERSION=$TRAVIS_BRANCH
fi

echo "Preparing to deply $VERSION, press ctrl-c to cancel"

sleep 1

r=./rancher

$r ps

function up() {
    $r up --file rancher-docker-compose.yml --stack converser -d $@
}

up --pull --upgrade --batch-size 1 --interval 60000 rethinkdb
$r wait converser/rethinkdb
up --confirm-upgrade rethinkdb

up --pull --upgrade --batch-size 1 --interval 60000 rethinkdb-joiner
$r wait converser/rethinkdb-joiner
up --confirm-upgrade rethinkdb-joiner

up --pull --upgrade --batch-size 2 --interval 20000 api
$r wait converser/api
up --confirm-upgrade api

up --pull --upgrade --batch-size 2 --interval 20000 call
$r wait converser/call
up --confirm-upgrade call

up --pull --upgrade --batch-size 2 --interval 20000 www
$r wait converser/www
up --confirm-upgrade www
