#!/bin/bash

$(./create_env.sh prod)

if [ "$TRAVIS_BRANCH" == "" ]; then
    export VERSION=$(git describe --abbrev=0)
else
    export VERSION=$TRAVIS_BRANCH
fi

echo "Preparing to deply $VERSION, press ctrl-c to cancel"

sleep 1

rancher ps

r=$(which rancher)

function up() {
    $r up --file rancher-docker-compose.yml --stack converser -d $@
}

up --pull --upgrade --batch-size 1 --interval 60000 rethinkdb
rancher wait converser/rethinkdb
up --confirm-upgrade rethinkdb

up --pull --upgrade --batch-size 1 --interval 60000 rethinkdb-joiner
rancher wait converser/rethinkdb-joiner
up --confirm-upgrade rethinkdb-joiner

up --pull --upgrade --batch-size 2 --interval 20000 api
rancher wait converser/api
up --confirm-upgrade api

up --pull --upgrade --batch-size 2 --interval 20000 call
rancher wait converser/call
up --confirm-upgrade call

up --pull --upgrade --batch-size 2 --interval 20000 www
rancher wait converser/www
up --confirm-upgrade www
