#!/bin/bash

convertC() {
    echo ${1#"/mnt"}
}

convertWin() {
    declare start=${1#"/"}
    start=${start:0:1}:${start:1}
    echo $start | sed 's#/#\\#g'
}

target=$(convertC $(pwd -P))
source=$(convertWin $(convertC $(pwd -P)))

docker run \
    -it \
    --rm \
    -v "$source:$target" \
    -w $target \
    -v /var/run/docker.sock:/var/run/docker.sock \
    docker/compose:1.8.0 \
    $@
