version: '3'
services:
  api:
    image: withinboredom/api:latest
    networks:
      - converser
    environment:
      - SMS
      - CALL
      - CALL_HOST
      - STRIPE_KEY
      - PLIVO_ID
      - PLIVO_TOKEN
      - DB_HOST=rethunk
    depends_on:
      - rethunk
    command: vendor/bin/aerys -d -c index.php
    deploy:
      mode: replicated
      replicas: 1
  engine:
    image: withinboredom/engine:latest
    networks:
      - converser
    environment:
      - SMS
      - CALL
      - CALL_HOST
      - STRIPE_KEY
      - PLIVO_ID
      - PLIVO_TOKEN
    depends_on:
      - rethunk
    ports:
      - '2200:80'
  web:
    image: withinboredom/site:latest
    networks:
      - converser
    ports:
      - '8090:8080'
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
  lb:
    image: traefik:latest
    ports:
      - '80:80'
      - '1337:1337'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - converser
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=traefik
      - --docker.watch
      - --web
  rethunk:
    image: rethinkdb:latest
    networks:
      - converser
    labels:
      - traefik.port=8080
    command:
      - bash
      - -c
      - rethinkdb create && exec rethinkdb --bind all --join rethunk
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: pause
        monitor: 30s
        max_failure_ratio: 0.1
      resources:
        reservations:
          cpus: '1'
          memory: 128M
      restart_policy:
        condition: any
        delay: 10s
        window: 10s
networks:
  converser:
